spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  sql:
    init:
      platform: h2
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
